language: python

git:
  depth: false

branches:
  only:
  - master
  - travisci
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

jobs:
  include:
  - services: docker
    env: CIBW_BUILD="cp35* cp36*" NPY_NUM_BUILD_JOBS=2
    arch: arm64
  - services: docker
    env: CIBW_SKIP="cp35* cp36*" NPY_NUM_BUILD_JOBS=2
    arch: arm64
  - services: docker
    arch: ppc64le
    # - services: docker
    #   arch: s390x
    # beta - Doesn't always work. Wait till Travis fixes.
    #
install:
- sudo rm -r $HOME/.cache
- python3 -m pip install --upgrade twine setuptools setuptools_scm pip cryptography
- python3 -m pip install cibuildwheel==1.5.2

script:
- sed -i '/numpy/d' pyproject.toml
- CIBW_BUILD_VERBOSITY=1 CIBW_ENVIRONMENT="SETUPTOOLS_SCM_PRETEND_VERSION=\"$TRAVIS_TAG\"" python3 -m cibuildwheel --output-dir dist

deploy:
  provider: pypi
  distributions: "--license" # Trick travis, see https://github.com/travis-ci/dpl/blob/577fb987337b6275f85cc104a38df30d030a860e/lib/dpl/providers/pypi.rb#L36
  username: "__token__"
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: CzkempBr8UTAa2J1vAY1vRBXRvgY0jJ1G8Q1tRigXAzwxHXwopYQ4ai4DF1hp9ecsOpxU7+1RYctvFEzmhDdDixxM3/Byc4ialeYM4bwS9Ynf9VtgkGQUGRjNLZJAcO3+8Npvu79XUgjuHOKUXjHPZSgd2V3Wo8JtDcW1v2DVeRtxD7EkXKRkLcH7IHmjLMRrZ0gkvS+U464zY63K64bdvSNHmCn/4aGpHki3VWxdZJfAZrKgBtdV6agmt3Vj/lBkvIYQLqqbKY74fdGPtky/w3OMY4whTO0xN5Lxz51Q/SAu9G5iN1gz3brvt4MxgzL35RnrGjq14brzPJndz1v4O4igYyvayROJ7ZXUsB9MlMKxNyXWrJ56JEHGWNWFf/m2+Icgrc2JPuLqxAa68EYVW+VkP+4aL1lxCLpGq+J0sutv8YtzpXQ9Ugv4a/wpUnRto9YfMettQFEZ262fHANzyNmhIdWRSHKHSxvK9Q36lnTVa90NaXq8ndsS0ZBvSCb6VTbZjbj7HjQC0ee1yMT1hHQOCnefo7XaiCbWqqGXeth5AoyXfVXKP/abJdVWqdXLyPMCU6xzQVUOuyafAJcZejUuG+zFTUD7tOrWu+sjfl5Vbumvg9gvPhB5p4MTblLWjM793effm/87eo832DWV/ydbWRSMKaFGxXgtuDgGcs=
